server:
  port: 443
  ssl:
    key-store: /etc/letsenrypt/live/yoda-server.jointheleague.org/keystone.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: tomcat
security:
  require-ssl=true


