server:
  port: 8080
  ssl:
    key-store: /etc/letsencrypt/live/yoda-server.jointheleague.org/keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: tomcat
security:
  require-ssl=true


